PoliziaMunicipale_MVC/Controllers/VerbaliController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace PoliziaMunicipale_MVC.Controllers
{
    public class VerbaliController : Controller
    {

        private string connectionString;
        public static List<Verbale> listaverbali = new List<Verbale>();
        public ActionResult Index()
        {
            TempData["controllerDorigine"] = this.ControllerContext.RouteData.Values["controller"].ToString();
            connectionString = ConfigurationManager.ConnectionStrings["PoliziaMunicipale"].ConnectionString;
            SqlConnection conn = new SqlConnection(connectionString);
            try
            {
                conn.Open();
                SqlCommand queryVisualizzaVerbali = new SqlCommand(
                "SELECT Verbale.*, CONCAT(Anagrafica.Nome, ' ', Anagrafica.Cognome) AS NominativoTrasgressore " +
                "FROM Verbale " +
                "INNER JOIN Anagrafica ON Verbale.IdAnagrafica = Anagrafica.IdAnagrafica", conn);
                SqlDataReader readerVerbali = queryVisualizzaVerbali.ExecuteReader();
                while (readerVerbali.Read())
                {
                    Verbale verbale = new Verbale
                    {
                        IdVerbale = Convert.ToInt32(readerVerbali["IdVerbale"]),
                        DataViolazione = Convert.ToDateTime(readerVerbali["DataViolazione"]),
                        IndirizzoViolazione = readerVerbali["IndirizzoViolazione"].ToString(),
                        NominativoAgente = readerVerbali["Nominativo_Agente"].ToString(),
                        DataTrascrizioneVerbale = Convert.ToDateTime(readerVerbali["DataTrascrizioneVerbale"]),
                        Importo = Convert.ToDecimal(readerVerbali["Importo"]),
                        DecurtamentoPunti = Convert.ToInt32(readerVerbali["DecurtamentoPunti"]),
                        NominativoTrasgressore = readerVerbali["NominativoTrasgressore"].ToString(),
                        IdViolazione = Convert.ToInt32(readerVerbali["IdViolazione"])
                    };
                    listaverbali.Add(verbale);
                }
            }
            catch
            {

            }
            finally { conn.Close(); }
            return View(listaverbali);
        }

        public ActionResult Create()
        {
            connectionString = ConfigurationManager.ConnectionStrings["PoliziaMunicipale"].ConnectionString;

            List<Anagrafica> listaanagrafica = Anagrafica.GetDataFromDB(connectionString);
            List<SelectListItem> listaAnagrafica = Anagrafica.ToSelectItems(listaanagrafica);

            List<TipoDiViolazione> listaviolazioni = TipoDiViolazione.GetDataFromDB(connectionString);
            List<SelectListItem> listaViolazioni = TipoDiViolazione.ToSelectList(listaviolazioni);

            ViewBag.ListaAnagrafica = listaAnagrafica;
            ViewBag.ListaViolazioni = listaViolazioni;
            return View();
        }

        [HttpPost]
        public ActionResult Create(Verbale nuovoverbale)
        {
            connectionString = ConfigurationManager.ConnectionStrings["PoliziaMunicipale"].ConnectionString;
            SqlConnection conn = new SqlConnection(connectionString);
            try
            {
                conn.Open();
                SqlCommand queryRegistraVerbale = new SqlCommand("INSERT INTO Verbale (DataViolazione, IndirizzoViolazione, Nominativo_Agente, DataTrascrizioneVerbale, Importo, DecurtamentoPunti, IdAnagrafica, IdViolazione) " +
                "VALUES (@DataViolazione, @IndirizzoViolazione, @NominativoAgente, @DataTrascrizioneVerbale, @Importo, @DecurtamentoPunti, @IdAnagrafica, @IdViolazione)", conn);

                queryRegistraVerbale.Parameters.AddWithValue("@DataViolazione", nuovoverbale.DataViolazione);
                queryRegistraVerbale.Parameters.AddWithValue("@IndirizzoViolazione", nuovoverbale.IndirizzoViolazione);
                queryRegistraVerbale.Parameters.AddWithValue("@NominativoAgente", nuovoverbale.NominativoAgente);
                queryRegistraVerbale.Parameters.AddWithValue("@DataTrascrizioneVerbale", nuovoverbale.DataTrascrizioneVerbale);
                queryRegistraVerbale.Parameters.AddWithValue("@Importo", nuovoverbale.Importo);
                queryRegistraVerbale.Parameters.AddWithValue("@DecurtamentoPunti", nuovoverbale.DecurtamentoPunti);
                queryRegistraVerbale.Parameters.AddWithValue("@IdAnagrafica", nuovoverbale.IdAnagrafica);
                queryRegistraVerbale.Parameters.AddWithValue("@IdViolazione", nuovoverbale.IdViolazione);

                int registrazioneeffettuata = queryRegistraVerbale.ExecuteNonQuery();
            }
            catch(Exception ex)
            {
                
            }
            finally { conn.Close(); }

            return RedirectToAction("Index");
        }
        public ActionResult VisualizzaTotaleVerbali()
        {
            connectionString = ConfigurationManager.ConnectionStrings["PoliziaMunicipale"].ConnectionString;
            SqlConnection conn = new SqlConnection(connectionString);
            List<TrasgressoreVerbale> trasgressoriVerbali = new List<TrasgressoreVerbale>();

            try
            {
                conn.Open();
                SqlCommand queryVisualizzaTotaleVerbaliPerTrasgressore = new SqlCommand(@"
            SELECT
                Verbale.IdAnagrafica,
                Anagrafica.Nome AS NomeTrasgressore,
                Anagrafica.Cognome AS CognomeTrasgressore,
                COUNT(*) AS TotaleVerbaliTrascritti
            FROM Verbale
            INNER JOIN Anagrafica ON Verbale.IdAnagrafica = Anagrafica.IdAnagrafica
            GROUP BY Verbale.IdAnagrafica, Anagrafica.Nome, Anagrafica.Cognome", conn);

                SqlDataReader reader = queryVisualizzaTotaleVerbaliPerTrasgressore.ExecuteReader();

                while (reader.Read())
                {
                    TrasgressoreVerbale trasgressoreVerbali = new TrasgressoreVerbale
                    {
                        IdAnagrafica = Convert.ToInt32(reader["IdAnagrafica"]),
                        NomeTrasgressore = reader["NomeTrasgressore"].ToString(),
                        CognomeTrasgressore = reader["CognomeTrasgressore"].ToString(),
                        TotaleVerbaliTrascritti = Convert.ToInt32(reader["TotaleVerbaliTrascritti"])
                    };

                    trasgressoriVerbali.Add(trasgressoreVerbali);
                }
            }
            catch (Exception ex)
            {
            }
            finally
            {
                conn.Close();
            }

            return View(trasgressoriVerbali);
        }

        public ActionResult VisualizzaTotalePunti()
        {
            connectionString = ConfigurationManager.ConnectionStrings["PoliziaMunicipale"].ConnectionString;
            SqlConnection conn = new SqlConnection(connectionString);
            List<TrasgressorePunti> trasgressoriPuntiDecurtati = new List<TrasgressorePunti>();

            try
            {
                conn.Open();
                SqlCommand queryVisualizzaTotalePuntiDecurtatiPerTrasgressore = new SqlCommand(@"
            SELECT
                Verbale.IdAnagrafica,
                Anagrafica.Nome AS NomeTrasgressore,
                Anagrafica.Cognome AS CognomeTrasgressore,
                SUM(Verbale.DecurtamentoPunti) AS TotalePuntiDecurtati
            FROM Verbale
            INNER JOIN Anagrafica ON Verbale.IdAnagrafica = Anagrafica.IdAnagrafica
            GROUP BY Verbale.IdAnagrafica, Anagrafica.Nome, Anagrafica.Cognome", conn);

                SqlDataReader reader = queryVisualizzaTotalePuntiDecurtatiPerTrasgressore.ExecuteReader();

                while (reader.Read())
                {
                    TrasgressorePunti trasgressorePuntiDecurtati = new TrasgressorePunti
                    {
                        IdAnagrafica = Convert.ToInt32(reader["IdAnagrafica"]),
                        NomeTrasgressore = reader["NomeTrasgressore"].ToString(),
                        CognomeTrasgressore = reader["CognomeTrasgressore"].ToString(),
                        TotalePuntiDecurtati = Convert.ToInt32(reader["TotalePuntiDecurtati"])
                    };

                    trasgressoriPuntiDecurtati.Add(trasgressorePuntiDecurtati);
                }
            }
            catch (Exception ex)
            {
                ViewBag.MessaggioErrore =  ex.Message;
            }
            finally
            {
                conn.Close();
            }

            return View(trasgressoriPuntiDecurtati);
        }

        public ActionResult VisualizzaViolazioniDieci()
        {
            connectionString = ConfigurationManager.ConnectionStrings["PoliziaMunicipale"].ConnectionString;
            SqlConnection conn = new SqlConnection(connectionString);
            List<ViolazionePuntiDieciQuattrocento> listaViolazionePuntiDieci = new List<ViolazionePuntiDieciQuattrocento>();

            try
            {
                conn.Open();
                SqlCommand queryVisualizzaViolazioniDieci = new SqlCommand(@"
            SELECT
                Verbale.Importo,
                Anagrafica.Cognome AS CognomeTrasgressore,
                Anagrafica.Nome AS NomeTrasgressore,
                Verbale.DataViolazione,
                Verbale.DecurtamentoPunti
            FROM Verbale
            INNER JOIN Anagrafica ON Verbale.IdAnagrafica = Anagrafica.IdAnagrafica
            WHERE Verbale.DecurtamentoPunti > 10", conn);

                SqlDataReader reader = queryVisualizzaViolazioniDieci.ExecuteReader();

                while (reader.Read())
                {
                    ViolazionePuntiDieciQuattrocento violazionePuntiDieci = new ViolazionePuntiDieciQuattrocento
                    {

PoliziaMunicipale_MVC/Views/Verbali/Create.cshtml
@model PoliziaMunicipale_MVC.Verbale

@{
    ViewBag.Title = "Create";
}
<nav class="navbar navbar-expand-lg navbar-light bg-primar text-white">

    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                @Html.ActionLink("Violazioni per anagrafica", "VisualizzaTotaleVerbaliTrascrittiPerTrasgressore", "Verbali", new { @class = "nav-link" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Violazioni per punti", "VisualizzaTotalePuntiDecurtatiPerTrasgressore", "Verbali", new { @class = "nav-link" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Violazioni per punti (10)", "VisualizzaViolazioniDieci", "Verbali", new { @class = "nav-link" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Violazioni per importo (400)", "VisualizzaViolazioniConImportoElevato", "Verbali", new { @class = "nav-link" })
            </li>

        </ul>
    </div>
</nav>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4 class="text-primary">Nuovo verbale</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.DataViolazione, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DataViolazione, new { htmlAttributes = new { type = "date", @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DataViolazione, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IndirizzoViolazione, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.IndirizzoViolazione, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IndirizzoViolazione, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NominativoAgente, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NominativoAgente, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NominativoAgente, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DataTrascrizioneVerbale, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DataTrascrizioneVerbale, new { htmlAttributes = new { type = "date", @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DataTrascrizioneVerbale, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Importo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Importo, new { htmlAttributes = new { type = "number", @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Importo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DecurtamentoPunti, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DecurtamentoPunti, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DecurtamentoPunti, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IdAnagrafica, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model=>model.IdAnagrafica, new SelectList(ViewBag.ListaAnagrafica, "Value", "Text"), "-- Seleziona trasgressore --", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IdAnagrafica, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IdViolazione, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.IdViolazione, new SelectList(ViewBag.ListaViolazioni, "Value", "Text"), "-- Seleziona violazione --", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IdViolazione, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <br />
            <input type="submit" value="Inserisci nuovo verbale" class="btn btn-outline-primary" />
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PoliziaMunicipale_MVC/Views/Verbali/Index.cshtml
@model IEnumerable<PoliziaMunicipale_MVC.Verbale>

@{
    ViewBag.Title = "Index";
}

<nav class="navbar navbar-expand-lg navbar-light">

    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                @Html.ActionLink("Violazioni per anagrafica", "VisualizzaTotaleVerbali", "Verbali", new { @class = "nav-link text-primary fw-bolder" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Violazioni per punti", "VisualizzaTotalePunti", "Verbali", new { @class = "nav-link text-primary fw-bolder" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Violazioni per punti (10)", "VisualizzaViolazioniDieci", "Verbali", new { @class = "nav-link text-primary fw-bolder" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Violazioni per importo (400)", "VisualizzaViolazioniQuattrocento", "Verbali", new { @class = "nav-link text-primary fw-bolder" })
            </li>

        </ul>
    </div>
</nav>

<p>
    @Html.ActionLink("Inserisci nuovo verbale", "Login", "Login", null, new { @class = "btn btn-outline-primary" })
</p>
<table class="table">
    <tr style="background-color: #007bff; color: white;">
        <th>
            @Html.DisplayNameFor(model => model.IdVerbale)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataViolazione)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IndirizzoViolazione)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NominativoAgente)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataTrascrizioneVerbale)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Importo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DecurtamentoPunti)
        </th>
        <th>
            Nominativo trasgressore
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdViolazione)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IdVerbale)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataViolazione)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IndirizzoViolazione)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NominativoAgente)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataTrascrizioneVerbale)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Importo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DecurtamentoPunti)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NominativoTrasgressore)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdViolazione)
        </td>

    </tr>
}

</table>

PoliziaMunicipale_MVC/Views/Verbali/VisualizzaTotalePunti.cshtml
@model List<TrasgressorePunti>

<nav class="navbar navbar-expand-lg navbar-light">

    <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                @Html.ActionLink("Violazioni per anagrafica", "VisualizzaTotaleVerbali", "Verbali", new { @class = "nav-link text-primary fw-bolder" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Violazioni per punti", "VisualizzaTotalePunti", "Verbali", new { @class = "nav-link text-primary fw-bolder" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Violazioni per punti (10)", "VisualizzaViolazioniDieci", "Verbali", new { @class = "nav-link text-primary fw-bolder" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Violazioni per importo (400)", "VisualizzaViolazioniQuattrocento", "Verbali", new { @class = "nav-link text-primary fw-bolder" })
            </li>

        </ul>
    </div>
</nav>

<h4 class="text-bg-primary text-center p-2">Totale punti decurtati per trasgressore</h4>

<table class="table">
    <thead>
        <tr style="background-color: #007bff; color: white;">
            <th>Nome</th>
            <th>Cognome</th>
            <th>Totale punti decurtati</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var trasgressore in Model)
        {
            <tr>
                <td>@trasgressore.NomeTrasgressore</td>
                <td>@trasgressore.CognomeTrasgressore</td>
                <td>@trasgressore.TotalePuntiDecurtati</td>
            </tr>
        }
    </tbody>
</table>

PoliziaMunicipale_MVC/Views/Verbali/VisualizzaTotalePuntiDecurtatiPerTrasgressore.cshtml
@model List<TrasgressorePunti>

<nav class="navbar navbar-expand-lg navbar-light">

    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                @Html.ActionLink("Violazioni per anagrafica", "VisualizzaTotaleVerbaliTrascrittiPerTrasgressore", "Verbali", new { @class = "nav-link" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Violazioni per punti", "VisualizzaTotalePuntiDecurtatiPerTrasgressore", "Verbali", new { @class = "nav-link" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Violazioni per punti (10)", "VisualizzaViolazioniDieci", "Verbali", new { @class = "nav-link" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Violazioni per importo (400)", "VisualizzaViolazioniConImportoElevato", "Verbali", new { @class = "nav-link" })
            </li>

        </ul>
    </div>
</nav>

<h2>Totale punti decurtati per trasgressore</h2>

<table class="table">
    <thead>
        <tr style="background-color: #007bff; color: white;">
            <th>Nome</th>
            <th>Cognome</th>
            <th>Totale Punti Decurtati</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var trasgressore in Model)
        {
            <tr>
                <td>@trasgressore.NomeTrasgressore</td>
                <td>@trasgressore.CognomeTrasgressore</td>
                <td>@trasgressore.TotalePuntiDecurtati</td>
            </tr>
        }
    </tbody>
</table>

PoliziaMunicipale_MVC/Views/Verbali/VisualizzaTotaleVerbali.cshtml
@model List<TrasgressoreVerbale>

<nav class="navbar navbar-expand-lg navbar-light">

    <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                @Html.ActionLink("Violazioni per anagrafica", "VisualizzaTotaleVerbali", "Verbali", new { @class = "nav-link text-primary fw-bolder" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Violazioni per punti", "VisualizzaTotalePunti", "Verbali", new { @class = "nav-link text-primary fw-bolder" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Violazioni per punti (10)", "VisualizzaViolazioniDieci", "Verbali", new { @class = "nav-link text-primary fw-bolder" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Violazioni per importo (400)", "VisualizzaViolazioniQuattrocento", "Verbali", new { @class = "nav-link text-primary fw-bolder" })
            </li>

        </ul>
    </div>
</nav>

<h4 class="text-bg-primary text-center p-2">Totale verbali trascritti per trasgressore</h4>

<table class="table">
    <thead>
        <tr style="background-color: #007bff; color: white;">
            <th>Nome</th>
            <th>Cognome</th>
            <th>Totale verbali trascritti</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var trasgressore in Model)
        {
            <tr>
                <td>@trasgressore.NomeTrasgressore</td>
                <td>@trasgressore.CognomeTrasgressore</td>
                <td>@trasgressore.TotaleVerbaliTrascritti</td>
            </tr>
        }
    </tbody>
</table>

PoliziaMunicipale_MVC/Views/Verbali/VisualizzaTotaleVerbaliTrascrittiPerTrasgressore.cshtml
@model List<TrasgressoreVerbale>

<nav class="navbar navbar-expand-lg navbar-light">

    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                @Html.ActionLink("Violazioni per anagrafica", "VisualizzaTotaleVerbaliTrascrittiPerTrasgressore", "Verbali", new { @class = "nav-link" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Violazioni per punti", "VisualizzaTotalePuntiDecurtatiPerTrasgressore", "Verbali", new { @class = "nav-link" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Violazioni per punti (10)", "VisualizzaViolazioniDieci", "Verbali", new { @class = "nav-link" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Violazioni per importo (400)", "VisualizzaViolazioniConImportoElevato", "Verbali", new { @class = "nav-link" })
            </li>

        </ul>
    </div>
</nav>

<h2>Totale verbali trascritti per trasgressore</h2>

<table class="table">
    <thead>
        <tr style="background-color: #007bff; color: white;">
            <th>Nome</th>
            <th>Cognome</th>
            <th>Totale Verbali Trascritti</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var trasgressore in Model)
        {
            <tr>
                <td>@trasgressore.NomeTrasgressore</td>
                <td>@trasgressore.CognomeTrasgressore</td>
                <td>@trasgressore.TotaleVerbaliTrascritti</td>
            </tr>
        }
    </tbody>
</table>

PoliziaMunicipale_MVC/Views/Verbali/VisualizzaViolazioniConImportoElevato.cshtml
@model List<ViolazionePuntiDieciQuattrocento>

<nav class="navbar navbar-expand-lg navbar-light">

    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                @Html.ActionLink("Violazioni per anagrafica", "VisualizzaTotaleVerbaliTrascrittiPerTrasgressore", "Verbali", new { @class = "nav-link" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Violazioni per punti", "VisualizzaTotalePuntiDecurtatiPerTrasgressore", "Verbali", new { @class = "nav-link" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Violazioni per punti (10)", "VisualizzaViolazioniDieci", "Verbali", new { @class = "nav-link" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Violazioni per importo (400)", "VisualizzaViolazioniConImportoElevato", "Verbali", new { @class = "nav-link" })
            </li>

        </ul>
    </div>
</nav>

<h2>Violazioni con importo superiore a 400 euro</h2>

<table class="table">
    <thead>
        <tr style="background-color: #007bff; color: white;">
            <th>Importo</th>
            <th>Cognome Trasgressore</th>
            <th>Nome Trasgressore</th>
            <th>Data Violazione</th>
            <th>Decurtamento Punti</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var violazione in Model)
        {
            <tr>
                <td>@violazione.Importo.ToString("C")</td>
                <td>@violazione.CognomeTrasgressore</td>
                <td>@violazione.NomeTrasgressore</td>
                <td>@violazione.DataViolazione.ToString("dd/MM/yyyy")</td>
                <td>@violazione.DecurtamentoPunti</td>
            </tr>
        }
    </tbody>
</table>